// Supabase 接続情報（anonキーは公開してよい設計の値）
export const SUPABASE_URL = "https://dmixilrcxiofanwfhxfq.supabase.co";
export const SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtaXhpbHJjeGlvZmFud2ZoeGZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY2NjM5MjUsImV4cCI6MjEwMjIzOTkyNX0.Ah-iFa87O3ysZN2eJBRUbUhcVhe8Gul4TXfNxfUt_f4";
